vich_uploader:
  db_driver: orm

  mappings:
    project_images:
      uri_prefix: /uploads/images/projects
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      upload_destination: '%kernel.project_dir%/public/uploads/images/projects'
