# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  # error_controller: App\Controller\ErrorController::show

  # the IP address (or range) of your proxy
  trusted_proxies: '127.0.0.1,REMOTE_ADDR'
  # trust *all* "X-Forwarded-*" headers
  trusted_headers: [ 'x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port' ]